import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'GOVERNANCE',
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'Build & Operate',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'operations'}],
    },
    {
      type: 'category',
      label: 'Tokenomics',
      items: [{type: 'autogenerated', dirName: 'tokenomics'}],
    },
    {
      type: 'category',
      label: 'Security',
      items: [{type: 'autogenerated', dirName: 'security'}],
    },
    {
      type: 'category',
      label: 'Roadmap',
      items: [{type: 'autogenerated', dirName: 'roadmap'}],
    },
  ],
};

export default sidebars;
